// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAllBooks() {
  return window['go']['books']['BookController']['GetAllBooks']();
}

export function SaveBook(arg1) {
  return window['go']['books']['BookController']['SaveBook'](arg1);
}
