// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {books} from '../models';

export function SaveBook(arg1:books.Book):Promise<void>;
