// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteBookById(arg1) {
  return window['go']['books']['BookController']['DeleteBookById'](arg1);
}

export function ExportBook(arg1) {
  return window['go']['books']['BookController']['ExportBook'](arg1);
}

export function GetAllBooks() {
  return window['go']['books']['BookController']['GetAllBooks']();
}

export function GetBookById(arg1) {
  return window['go']['books']['BookController']['GetBookById'](arg1);
}

export function SaveBook(arg1) {
  return window['go']['books']['BookController']['SaveBook'](arg1);
}

export function SavePdf(arg1) {
  return window['go']['books']['BookController']['SavePdf'](arg1);
}

export function UpdateBook(arg1) {
  return window['go']['books']['BookController']['UpdateBook'](arg1);
}
