// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {user} from '../models';

export function GetUserConfig():Promise<user.UserConfig>;

export function SelectFolder():Promise<string>;

export function UpdateUserConfig(arg1:user.UserConfig):Promise<void>;
