// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetUserConfig() {
  return window['go']['user']['userController']['GetUserConfig']();
}

export function UpdateUserConfig(arg1) {
  return window['go']['user']['userController']['UpdateUserConfig'](arg1);
}
